<a href="https://colab.research.google.com/github/MeghaBharti/Chal_Pytorch_Sikhe/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [1]:
data=[[1,2],[3,4]]

In [5]:
x= torch.tensor(data)
x

tensor([[1, 2],
        [3, 4]])

In [6]:
#from numpy array
np_array= np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [8]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [10]:
x_ones = torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [11]:
tensor = torch.rand(3,4)
tensor

tensor([[0.1900, 0.6642, 0.0991, 0.5059],
        [0.6871, 0.8741, 0.1626, 0.1593],
        [0.1150, 0.5270, 0.5897, 0.6925]])

In [13]:
tensor.shape

torch.Size([3, 4])

In [14]:
tensor.dtype

torch.float32

In [17]:
tensor.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
  tensor= tensor.to('cuda')

In [18]:
tensor = torch.ones(4,4)
#first row
tensor[0]

tensor([1., 1., 1., 1.])

In [19]:
#first column
tensor[:,0]

tensor([1., 1., 1., 1.])

In [20]:
#last column
tensor[...,-1]

tensor([1., 1., 1., 1.])

In [21]:
#second column
tensor[:,1]=0


In [22]:
tensor[:,1]

tensor([0., 0., 0., 0.])

In [23]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
t1= torch.cat([tensor,tensor,tensor],dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [27]:
t1= torch.cat([tensor,tensor],dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [ ]:
#Arithmetic Operations
